### PR TITLE
Bug:#110 changed progress indicator color for better view

### PR DESCRIPTION
**Pull request by tavkeer**
### Description
Changed the progress indicator colour

### Proposed Changes
The circle Progress indicator had same background and active colour which posed difficult to see if it is loading or not 
so i changes one of the two colour for better viewing 

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by MarkisDev** [comment]
Could you add some screenshots/video to show the change?

**Comment by tavkeer** [comment]
@MarkisDev 
Actually it is happening so fast it's not possible to capture the video but I'll try

**Comment by tavkeer** [comment]
@MarkisDev 
here is the video check this?

https://github.com/CCExtractor/ultimate_alarm_clock/assets/105163810/f932c255-4c94-4650-bd51-0cd915311c1f

**Comment by tavkeer** [comment]
the double background colour that was hindring the view of this is removed

**Comment by MarkisDev** [comment]
@tavkeer could you please resolve the merge conflicts and update the PR?

**Comment by tavkeer** [comment]
Yep just a moment

**Comment by tavkeer** [comment]
@MarkisDev 
I updated this can you merge this

**Review by MarkisDev — APPROVED** [review]

**Pull request merged**
