### PR TITLE
Add options to select days while adding/updating an alarm

### LINKED ISSUE #222: Feature: Repetition of alarm - Improved Alarm Setup
## Description: 
Reference: #204 'I'm trying to setup a one-time alarm for Monday, but I can't (there's no way to select the day of the week for a one time alarm). I saw I can select the day of the week under the Repeat field. I think it would be better to call that field "Days of the week" then, and by default select the one in which the alarm would ring (i.e. today or tomorrow, depending on the current time and the alarm time).
-Repeat once is confusing. Does it mean it would ring twice?'

## Proposed solution:
I suggest introducing a 'Repeat' dialog with four clear options:

- Once: For a single occurrence (the next day).
- Daily: Automatically selects the whole week.
- Weekdays: Selects Monday to Friday (excluding the weekend).
- Custom: Provides flexibility for users to select their preferred days (As it is now).

I would like to work on this issue, so please consider assigning it to me.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by its-me-abhishek**
### Description

- Changed the Repeat once tile's name to `Ring once`
- Added 2 more options to select days easily:
   - Daily
   - Weekends

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by MarkisDev** [comment]
I can see this will work, but I was thinking of making the daily and weekends sort of like a button (something like the Alarm offsets option) 

The checkboxes can be left as is, when the values match, we can enable the associated button as selected - for ex :

If you check all days, the Days button would show selected, if you click it, it will unselect all days. 

Same with weekends.

**Review by MarkisDev — CHANGES_REQUESTED** [review]
Making the Weekday and Daily a button

**Comment by its-me-abhishek** [comment]
I have thought of another approach that may look and match the overall ui. We can make all of this into a bottom sheet and add these 3 options there, Daily, Weekdays, Custom, this older dialog pops up if custom is selected.

**Comment by MarkisDev** [comment]
> I have thought of another approach that may look and match the overall ui. We can make all of this into a bottom sheet and add these 3 options there, Daily, Weekdays, Custom, this older dialog pops up if custom is selected. As buttons may make this dialog box a bit too large

This also sounds like a great approach.

**Comment by its-me-abhishek** [comment]
I have implemented the feature, have checked for the edge cases as well, we cannot choose multiple options at the same time.

**Review by MarkisDev — APPROVED** [review]

**Pull request merged**
