### PR TITLE
Input time in textFields using keyboard

### LINKED ISSUE #124: Feature: Option to choose time by adding it through soft keyboard.
### Description

The only available option to choose time is by scrolling the digits available for hours ,minutes and period of the day. An alternate option for selecting time using soft keys by directly entering digits might provide a better user experience. I can work on this issue if it is assigned to me.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by SATVIKSH**
### Description
Alternate option to add time using textfield has been added. You can toggle between textfields and datepicker by tapping once.

## Screenshots

Screenshot

### CODE REVIEW

**Comment by MarkisDev** [comment]
Hey, could you add something to demonstrate the working?

**Comment by SATVIKSH** [comment]
> Hey, could you add something to demonstrate the working?

This is a video demonstrating the feature I added.

https://github.com/CCExtractor/ultimate_alarm_clock/assets/94671974/e9a875ae-f6f1-410c-b909-f1fbcbcc386a

**Comment by SATVIKSH** [comment]
The problem  mentioned in the issue #158 has been solved with this pull request as well.

https://github.com/CCExtractor/ultimate_alarm_clock/assets/94671974/052c4908-6410-4c8b-980b-d248383597ae

**Review by MarkisDev — APPROVED** [review]

**Comment by MarkisDev** [comment]
Looks like the codebase is getting bigger, I'll look into splitting the controller functions into separate files for readability. Good work!

**Pull request merged**
