### PR TITLE
fix: Timer Functionality Issue When App is Backgrounded

### LINKED ISSUE #494: Bug: Timer Functionality Issue When App is Backgrounded
### Description

When a timer is set and initiated within the app, the timer functions correctly initially. However, if I switch away from the app without even closing it entirely, the timer's functionality becomes erratic. Instead of decrementing by one second at a time, the timer's countdown accelerates, resulting in incorrect time measurements. Attempting to pause the timer after that is also not working. Moreover, attempting to set and initiate a new timer after encountering this issue also results in the acceleration of the countdown. Please assign this issue to me!

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/83498152/f945c615-7e12-4ed2-8afa-74c04ad096df

### PR DESCRIPTION
**Pull request by oops-shlok**
### Description
This PR fixes the issue in the timerController where the timer countdown would accelerate when the app was backgrounded and resumed.

### Proposed Changes
- Implemented logic to properly handle app lifecycle state changes using the didChangeAppLifecycleState method. When the app is resumed, the timer will only start if it was running and not paused before the app was backgrounded.
- Modified the startTimer and stopTimer methods to properly handle the cancellation and initialisation of the countdown timer.

## Screenshots
https://github.com/CCExtractor/ultimate_alarm_clock/assets/83498152/3ee2fb5b-dfde-4836-b484-34ea79bf9a4e

## Checklist
- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by SATVIKSH** [comment]
Hey, @oops-shlok  I would like to point out some adjustments to your latest commit,
1) The reason why this bug occured was because of the faulty use of app lifecycle. When the application was being brought to focus the app was running loadTimerFromStorage() method which led to the start of another timer over the previously running timer(2 timers running simultaneously hence it was skipping 2 values in one second). So the issue could've been solved by simply removing this method.
2) The methods you've removed from resumeTimer() and pauseTimer() are necessary for the notification of timer completion(which requires some adjustments to be working correctly).

**Comment by oops-shlok** [comment]
> Hey, @oops-shlok I would like to point out some adjustments to your latest commit,
> 
> 1. The reason why this bug occured was because of the faulty use of app lifecycle. When the application was being brought to focus the app was running loadTimerFromStorage() method which led to the start of another timer over the previously running timer(2 timers running simultaneously hence it was skipping 2 values in one second). So the issue could've been solved by simply removing this method.
> 2. The methods you've removed from resumeTimer() and pauseTimer() are necessary for the notification of timer completion(which requires some adjustments to be working correctly).

Hey @SATVIKSH, i understood the points you mentioned. I’ll update them accordingly. Thanks for pointing out the adjustments.

**Comment by oops-shlok** [comment]
> Hey, @oops-shlok I would like to point out some adjustments to your latest commit,
> 
> 1. The reason why this bug occured was because of the faulty use of app lifecycle. When the application was being brought to focus the app was running loadTimerFromStorage() method which led to the start of another timer over the previously running timer(2 timers running simultaneously hence it was skipping 2 values in one second). So the issue could've been solved by simply removing this method.
> 2. The methods you've removed from resumeTimer() and pauseTimer() are necessary for the notification of timer completion(which requires some adjustments to be working correctly).

I have updated the code now. I added a condition of '!isTimerRunning.value' to ensure that the timer state is only loaded from storage when the app is resumed and the timer is not already running. This prevents the duplication of timers and ensures that the decrement happens by 1 second

**Comment by oops-shlok** [comment]
@MarkisDev is this fine?

**Review by MarkisDev — APPROVED** [review]

**Pull request merged**
