### PR TITLE
Error screen while changing theme branch shivam rao

### LINKED ISSUE #125: Issue: In toggle button, When Light mode is enabled it is rarely visible.
### Description

When we press&hold the alarm tile to delete it the toggle button's circular border color and animated circle color both are white which only goes with the Dark Mode Theme.

### Screenshots

How to Produce this issue:-

https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/ef5f5e1f-402c-4009-9cd2-44b4e480e6f9

After fixing this issue:-

https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/429ba479-5a20-4505-ae9f-cf6bfdb5090c

### PR DESCRIPTION
**Pull request by shivam-rao-official**
## Fixes #125 

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by superiorsd10** [comment]
Hello @shivam-rao-official 👋
It's great to see you contributing, but you've to first ask for the issue to be assigned to you. You can't directly open a PR for any issue. So make sure you first get it assigned. 

Thank you,

**Comment by shivam-rao-official** [comment]
Ok I'll do the same as you mentioned.
Thanks for the information actually new in this Open Source Contribution and thus I need guidance for this information thank you

**Comment by shivam-rao-official** [comment]
> Hello @shivam-rao-official 👋
> It's great to see you contributing, but you've to first ask for the issue to be assigned to you. You can't directly open a PR for any issue. So make sure you first get it assigned. 
> 
> Thank you,

Ok I'll do the same as you mentioned.
Thanks for the information actually new in this Open Source Contribution and thus I need guidance for this information thank you

**Comment by sameermansoori1** [comment]
> > Hello @shivam-rao-official 👋
> > It's great to see you contributing, but you've to first ask for the issue to be assigned to you. You can't directly open a PR for any issue. So make sure you first get it assigned.
> > Thank you,
> 
> Ok I'll do the same as you mentioned. Thanks for the information actually new in this Open Source Contribution and thus I need guidance for this information thank you

@shivam-rao-official Then close this PR and let the maintainer decide the assignee.

**Comment by MarkisDev** [comment]
Fixed with #123

**Pull request closed without merging**
