### PR TITLE
Lap_added

### LINKED ISSUE #406: Feature: Adding Lap(Flag) in stopwatch  to track intervals
### Description

Adding a lap feature to an alarm clock enhances its functionality by allowing users to track time intervals, typically used during activities like running, exercising, or timing laps in sports events. The lap feature enables users to mark specific points in time, creating segments for easier monitoring and analysis.

Display lap times in a separate section or list within the interface.

When the user initiates a lap, record the current time and display it as a lap time.

Allow users to view lap times sequentially as they mark additional laps.

### Screenshots

WhatsApp Image 2024-01-30 at 6 10 3
Android Large - 1

### PR DESCRIPTION
**Pull request by Reetinder932**
### Description
The new lap functionality is added  

### Proposed Changes
Laps are added

## Screenshots
WhatsApp Image 2024-02-07 at 16 43 48_b21ceb7d

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by codesage01** [comment]
@Reetinder932, @MarkisDev, the issue has been assigned to me, I've been working on it from the past 4 days, and it's almost done,
So,. could you please close this PR

**Comment by MarkisDev** [comment]
> @Reetinder932, @MarkisDev, the issue has been assigned to me, I've been working on it from the past 4 days, and it's almost done, So,. could you please close this PR

I'll keep this issue open for a little longer since it was assigned to you and you've been working on it :)

**Comment by codesage01** [comment]
ok thanks!, Today i will makin PR.

**Comment by MarkisDev** [comment]
Closing this since it's stale. Feel free to reopen.

**Pull request closed without merging**
